title: Museum of Errors
email: burke9077@gmail.com
description: >- 
  Museumoferrors.com is an open-source site collecting data on Pokemon error cards.
baseurl: "https://museumoferrors.com"
url: "https://museumoferrors.com"
twitter_username: Burke9077
github_username:  Burke9077

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include:
  - _includes
  - _layouts
  - _pages
  - _posts

exclude: 
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github
  - README.md