title: Museum of Errors
email: burke9077@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Museumoferrors.com is an open-source site collecting data on Pokemon error cards.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://museumoferrors.com" # the base hostname & protocol for your site
twitter_username: Burke9077
github_username:  Burke9077

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed