name: Test, Build, and Publish Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run: rake test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write  # Ensure the token has write permissions

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure the full history is fetched
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build the site
      run: bundle exec jekyll build --destination ./_site
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
